Time lag stats
cesium-ml/cesium pull request #315
Opened 2023-04-12 23:34 UTC by JRKagumba

I extended cadence_features.py, with two new functions: compute_time_lag_stats and compute_time_lag_skew_kurtosis. The compute_time_lag_stats function calculates the mean and standard deviation of the time lags, while the compute_time_lag_skew_kurtosis function computes the skewness and kurtosis. The additions offer support for time lag distributions, offering insights into their central tendency, dispersion, and shape.

2023-04-14 23:58 UTC, profjsb requested changes
Looking good. Thank you for your first PR here! Could you add a short test for the new features (in `cesium/features/test/test_cadence_features.py`)?

2023-04-14 23:58 UTC, profjsb commented on cesium/features/cadence_features.py
> +    "compute_time_lag_skew_kurtosis"
```suggestion
    "compute_time_lag_skew_kurtosis",
```

2023-04-14 23:58 UTC, profjsb commented on cesium/features/graphs.py
> +        "time_lag_skew_kurtosis"
```suggestion
        "time_lag_skew_kurtosis",
```

2023-04-15 10:24 UTC, JRKagumba commented
Added test functions to validate the correctness of compute_time_lag_stats and compute_time_lag_skew_kurtosis by computing the mean, standard deviation, skewness, and kurtosis for a given array of time lags.

2023-04-19 04:14 UTC, profjsb approved these changes
@JRKagumba thanks again for your contribution. It turns out we have two of the four new features in the PR already.  Just so you know the four features are now called: "cads_avg", "cads_std", "cads_skew", and "cads_kurtosis".

To simplify the addition of the other two features I made use of `skew` and `kurtosis` helper functions in `common_functions.py`. The tests for these cadence statistics features looks like:

```python
def test_compute_time_lag_stats():
    """Test compute_time_lag_stats function."""
    times, values, errors = irregular_random(500)
    cads = np.diff(times)

    f = generate_features(
        times, values, errors, ["cads_avg", "cads_std", "cads_skew", "cads_kurtosis"]
    )
    npt.assert_almost_equal(f["cads_avg"], np.mean(cads))
    npt.assert_almost_equal(f["cads_std"], np.std(cads))
    npt.assert_almost_equal(f["cads_skew"], stats.skew(cads))
    npt.assert_almost_equal(f["cads_kurtosis"], stats.kurtosis(cads))
```

2023-04-19 04:15 UTC, merged